name: Testing
on: 
  pull_request: 

jobs: 
  Jest-test:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.15.0'
      - run: yarn install
      - run: yarn test
  




